// Design review screenshots (phone + desktop). usage: node scripts/review-shots.mjs <base> <outdir>
import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
const [base, dir] = process.argv.slice(2);
const p = spawn("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", ["--headless=new", "--hide-scrollbars", "--remote-debugging-port=0", "--user-data-dir=" + (process.env.TMPDIR || "/tmp") + "/ag-rs-" + process.pid, "about:blank"]);
const ws = new WebSocket(await new Promise((ok) => p.stderr.on("data", (d) => { const m = String(d).match(/ws:\/\/\S+/); if (m) ok(m[0]); })));
await new Promise((ok) => (ws.onopen = ok));
let id = 0; const pend = new Map(); const errs = [];
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (pend.has(m.id)) { pend.get(m.id)(m); pend.delete(m.id); } if (m.method === "Runtime.exceptionThrown") errs.push(m.params.exceptionDetails.exception?.description?.slice(0, 200)); };
const send = (method, params = {}, sessionId) => new Promise((ok) => { const i = ++id; pend.set(i, ok); ws.send(JSON.stringify({ id: i, method, params, sessionId })); });
const { result: { targetId } } = await send("Target.createTarget", { url: "about:blank" });
const { result: { sessionId } } = await send("Target.attachToTarget", { targetId, flatten: true });
await send("Runtime.enable", {}, sessionId);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const ev = async (x) => (await send("Runtime.evaluate", { expression: x, returnByValue: true }, sessionId)).result.result?.value;
const size = (w, h, mobile) => send("Emulation.setDeviceMetricsOverride", { width: w, height: h, deviceScaleFactor: 1, mobile }, sessionId);
const shot = async (f, full = false) => { const { result } = await send("Page.captureScreenshot", { format: "png", captureBeyondViewport: full }, sessionId); writeFileSync(`${dir}/${f}`, Buffer.from(result.data, "base64")); };
const go = async (route, wait = 3000) => { await send("Page.navigate", { url: base + "?r=" + Math.random() + route }, sessionId); await sleep(wait); };
const PEOPLE = JSON.stringify([{ id: "a1", name: "ലക്ഷ്മി", gender: "Female", date: "1958-07-21", time: "05:40", place: { name: "Tiruvalla, Kerala, India", lat: 9.3816, lon: 76.5749, tz: 5.5 } }, { id: "a2", name: "Anil", gender: "Male", date: "1985-03-02", time: "21:15", place: { name: "Kochi, Kerala, India", lat: 9.94, lon: 76.26, tz: 5.5 } }, { id: "a3", name: "മീര", gender: "Female", date: "2015-11-30", time: "07:05", place: { name: "Kozhikode, Kerala, India", lat: 11.25, lon: 75.78, tz: 5.5 } }]);
const L = "n=%E0%B4%B2%E0%B4%95%E0%B5%8D%E0%B4%B7%E0%B5%8D%E0%B4%AE%E0%B4%BF&g=F&d=1958-07-21&t=05:40&p=Tiruvalla%2C%20Kerala%2C%20India&la=9.3816&lo=76.5749&tz=5.5&id=a1";
await size(390, 844, true);
await go("#/"); await ev(`localStorage.clear(); localStorage.setItem('ag.ui', JSON.stringify({lang:'ml',theme:'light'}))`);
await go("#/"); await shot("m01-home-empty.png");
await ev(`localStorage.setItem('ag.charts', ${JSON.stringify(PEOPLE)})`);
await go("#/", 5000); await shot("m02-home.png");
await go("#/people", 5000); await shot("m03-people.png");
await go("#/person?for=horoscope"); await shot("m04-step1.png");
await ev(`document.querySelector('.big-input').value='ലക്ഷ്മി'; document.querySelector('.big-input').dispatchEvent(new Event('input')); document.querySelectorAll('.big-choice')[1].click(); document.querySelector('.btn-primary-xl').click();`); await sleep(400); await shot("m05-step2.png");
await ev(`const [d,t]=document.querySelectorAll('.big-input'); d.value='1958-07-21'; d.dispatchEvent(new Event('change')); t.value='05:40'; t.dispatchEvent(new Event('change')); document.querySelector('.btn-primary-xl').click();`); await sleep(500);
await ev(`document.querySelector('.combo input').focus()`); await send("Input.insertText", { text: "Tiruvalla" }, sessionId); await sleep(3000); await shot("m06-step3-search.png");
await go(`#/horoscope?${L}`, 5000); await ev(`localStorage.setItem('ag.ui', JSON.stringify({lang:'ml',theme:'light',expert:false}))`); await go(`#/horoscope?${L}`, 5000); await shot("m07-horo-simple.png"); await shot("m07b-horo-simple-full.png", true);
await ev(`document.querySelector('.expert-btn').click()`); await sleep(2500); await shot("m08-horo-expert.png");
await ev(`localStorage.setItem('ag.ui', JSON.stringify({lang:'ml',theme:'light',expert:false}))`);
await go(`#/ask?${L}`, 5000); await shot("m09-call.png");
await go("#/more"); await shot("m10-more.png");
await go("#/settings"); await shot("m11-settings.png");
await go("#/porutham"); await shot("m12-legacy.png");
await size(1280, 860, false);
await go("#/", 5000); await shot("d01-home.png");
await go(`#/horoscope?${L}`, 5000); await shot("d02-horo-simple.png");
await ev(`document.querySelector('.expert-btn').click()`); await sleep(2500); await shot("d03-horo-expert.png");
console.log("errors:", errs.length ? errs : "none");
ws.close(); p.kill(); process.exit(0);
